# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6ee46187dc8549f0c1b18b33a806bd530c6c6751aeb928b84afa780ee4c5db65a4bdc2a9f3f09d367c3797bf85cd6529723f6f1b43ef92821d568f1dd66be63

test:
  secret_key_base: c7a8c1eeefafb4bd406f2b73b5047625a5e527746c1745b64ac21b285a75279af20ecf1e8c173ad500411e0a6b1593d9ab7482d9f75d0a3686d9c1e9a8661012

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
